services:
    mafiascum.restApi.restApiController:
        class: mafiascum\restApi\controller\RestApi
        arguments:
            - '@controller.helper'
            - '@template'
            - '@request'
            - '@dbal.conn'
            - '@user'
            - '@user_loader'
            - '@language'
            - '@auth'